sylius_ui:
    events:
        # Index
        sylius.admin.index.body:
            blocks:
                sidebar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_sidebar.html.twig'
                navbar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_navbar.html.twig'
                content:
                    template: '@SyliusAdmin/Shared/Crud/Common/_content.html.twig'
        sylius.admin.index.body.content:
            blocks:
                flashes:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/_flashes.html.twig'
                header:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/_header.html.twig'
                grid:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/_grid.html.twig'
        sylius.admin.index.body.content.header:
            blocks:
                breadcrumbs:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Header/_breadcrumbs.html.twig'
                title_block:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/Header/_titleBlock.html.twig'
        sylius.admin.index.body.content.header.title_block:
            blocks:
                title:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/Header/TitleBlock/_title.html.twig'
                actions:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/Header/TitleBlock/_actions.html.twig'
        sylius.admin.index.body.content.grid:
            blocks:
                filters:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/_filters.html.twig'
                data_table:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/_dataTable.html.twig'
                no_data_block:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/_noResults.html.twig'
        sylius.admin.index.body.content.grid.no_results:
            blocks:
                image:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/NoResults/_image.html.twig'
                title:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/NoResults/_title.html.twig'
                subtitle:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/NoResults/_subtitle.html.twig'
                action:
                    template: '@SyliusAdmin/Shared/Crud/Index/Content/Grid/NoResults/_action.html.twig'

        # Create
        sylius.admin.create.body:
            blocks:
                sidebar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_sidebar.html.twig'
                navbar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_navbar.html.twig'
                content:
                    template: '@SyliusAdmin/Shared/Crud/Common/_content.html.twig'
        sylius.admin.create.body.content:
            blocks:
                flashes:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/_flashes.html.twig'
                header:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/_header.html.twig'
                form:
                    template: '@SyliusAdmin/Shared/Crud/Create/Content/_form.html.twig'
                    context:
                        render_rest: true
        sylius.admin.create.body.content.header:
            blocks:
                breadcrumbs:
                    template: '@SyliusAdmin/Shared/Crud/Create/Content/Header/_breadcrumbs.html.twig'
                title_block:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/Header/_titleBlock.html.twig'
        sylius.admin.create.body.content.header.title_block:
            blocks:
                title:
                    template: '@SyliusAdmin/Shared/Crud/Create/Content/Header/TitleBlock/_title.html.twig'

        # Update
        sylius.admin.update.body:
            blocks:
                sidebar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_sidebar.html.twig'
                navbar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_navbar.html.twig'
                content:
                    template: '@SyliusAdmin/Shared/Crud/Common/_content.html.twig'
        sylius.admin.update.body.content:
            blocks:
                flashes:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/_flashes.html.twig'
                header:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/_header.html.twig'
                form:
                    template: '@SyliusAdmin/Shared/Crud/Update/Content/_form.html.twig'
                    context:
                        render_rest: true
        sylius.admin.update.body.content.header:
            blocks:
                breadcrumbs:
                    template: '@SyliusAdmin/Shared/Crud/Update/Content/Header/_breadcrumbs.html.twig'
                title_block:
                    template: '@SyliusAdmin/Shared/Crud/Common/Content/Header/_titleBlock.html.twig'
        sylius.admin.update.body.content.header.title_block:
            blocks:
                title:
                    template: '@SyliusAdmin/Shared/Crud/Update/Content/Header/TitleBlock/_title.html.twig'
