sylius_ui:
    events:
        # Show
        sylius.admin.product.show.content:
            blocks:
                page_body:
                    template: '@SyliusAdmin/Product/Show/Content/_pageBody.html.twig'
        sylius.admin.product.show.content.header.title_block:
            blocks:
                title:
                    template: '@SyliusAdmin/Product/Show/Content/Header/TitleBlock/_title.html.twig'
        sylius.admin.product.show.content.page_body:
            blocks:
                details:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/_details.html.twig'
                translations:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/_translations.html.twig'
                taxonomy:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/_taxonomy.html.twig'
                associations:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/_associations.html.twig'
        sylius.admin.product.show.content.page_body.taxonomy:
            blocks:
                main_taxon:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/Taxonomy/_mainTaxon.html.twig'
                product_taxons:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/Taxonomy/_productTaxons.html.twig'
        sylius.admin.product.show.content.page_body.translations.translation_content:
            blocks:
                name:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/TranslationContent/_name.html.twig'
                slug:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/TranslationContent/_slug.html.twig'
                description:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/TranslationContent/_description.html.twig'
                short_description:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/TranslationContent/_shortDescription.html.twig'
                meta_keywords:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/TranslationContent/_metaKeywords.html.twig'
                meta_description:
                    template: '@SyliusAdmin/Product/Show/Content/PageBody/TranslationContent/_metaDescription.html.twig'
        
        # Update
        sylius.admin.product.update.content:
            blocks:
                form:
                    context:
                        render_rest: false
        sylius.admin.product.update.content.header.title_block:
            blocks:
                actions:
                    template: '@SyliusAdmin/Product/Update/Header/TitleBlock/_actions.html.twig'
        sylius.admin.product.update.content.header.title_block.actions:
            blocks:
                more:
                    template: '@SyliusAdmin/Product/Update/Header/TitleBlock/Actions/_more.html.twig'
                cancel:
                    template: '@SyliusAdmin/Product/Update/Header/TitleBlock/Actions/_cancel.html.twig'
                create:
                    template: '@SyliusAdmin/Product/Update/Header/TitleBlock/Actions/_update.html.twig'
        sylius.admin.product.update.content.header.title_block.actions.more:
            blocks:
                view_in_store:
                    template: '@SyliusAdmin/Product/Update/Header/TitleBlock/Actions/More/_viewInStore.html.twig'
        sylius.admin.product.update.content.form:
            blocks:
                form_body:
                    template: '@SyliusAdmin/Product/Form/formBody.html.twig'
        sylius.admin.product.update.content.form.form_body:
            blocks:
                side_navigation:
                    template: '@SyliusAdmin/Product/Form/_sideNavigation.html.twig'
                sections:
                    template: '@SyliusAdmin/Product/Form/_sections.html.twig'
        sylius.admin.product.update.content.form.form_body.side_navigation:
            blocks:
                details:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_details.html.twig'
                    context:
                        active: true
                channel_pricing:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_channelPricing.html.twig'
                inventory:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_inventory.html.twig'
                translations:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_translations.html.twig'
                taxonomy:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_taxonomy.html.twig'
                attributes:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_attributes.html.twig'
                associations:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_associations.html.twig'
                media:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_media.html.twig'
        sylius.admin.product.update.content.form.form_body.sections:
            blocks:
                details:
                    template: '@SyliusAdmin/Product/Form/Sections/_details.html.twig'
                translations:
                    template: '@SyliusAdmin/Product/Form/Sections/_translations.html.twig'
                taxonomy:
                    template: '@SyliusAdmin/Product/Form/Sections/_taxonomy.html.twig'
                attributes:
                    template: '@SyliusAdmin/Product/Form/Sections/_attributes.html.twig'
                associations:
                    template: '@SyliusAdmin/Product/Form/Sections/_associations.html.twig'
                media:
                    template: '@SyliusAdmin/Product/Form/Sections/_media.html.twig'
        # Create
        sylius.admin.product.create.content:
            blocks:
                form:
                    context:
                        render_rest: false
        sylius.admin.product.create.content.header.title_block:
            blocks:
                actions:
                    template: '@SyliusAdmin/Product/Create/Header/TitleBlock/_actions.html.twig'
        sylius.admin.product.create.content.header.title_block.actions:
            blocks:
                cancel:
                    template: '@SyliusAdmin/Product/Create/Header/TitleBlock/Actions/_cancel.html.twig'
                create:
                    template: '@SyliusAdmin/Product/Create/Header/TitleBlock/Actions/_create.html.twig'
        sylius.admin.product.create.content.form:
            blocks:
                form_body:
                    template: '@SyliusAdmin/Product/Form/formBody.html.twig'
        sylius.admin.product.create.content.form.form_body:
            blocks:
                side_navigation:
                    template: '@SyliusAdmin/Product/Form/_sideNavigation.html.twig'
                sections:
                    template: '@SyliusAdmin/Product/Form/_sections.html.twig'
        sylius.admin.product.create.content.form.form_body.side_navigation:
            blocks:
                details:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_details.html.twig'
                    context:
                        active: true
                channel_pricing:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_channelPricing.html.twig'
                inventory:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_inventory.html.twig'
                translations:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_translations.html.twig'
                taxonomy:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_taxonomy.html.twig'
                attributes:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_attributes.html.twig'
                associations:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_associations.html.twig'
                media:
                    template: '@SyliusAdmin/Product/Form/SideNavigation/_media.html.twig'
        sylius.admin.product.create.content.form.form_body.sections:
            blocks:
                details:
                    template: '@SyliusAdmin/Product/Form/Sections/_details.html.twig'
                channel_pricing:
                    template: '@SyliusAdmin/Product/Form/Sections/_channelPricing.html.twig'
                inventory:
                    template: '@SyliusAdmin/Product/Form/Sections/_inventory.html.twig'
                translations:
                    template: '@SyliusAdmin/Product/Form/Sections/_translations.html.twig'
                taxonomy:
                    template: '@SyliusAdmin/Product/Form/Sections/_taxonomy.html.twig'
                attributes:
                    template: '@SyliusAdmin/Product/Form/Sections/_attributes.html.twig'
                associations:
                    template: '@SyliusAdmin/Product/Form/Sections/_associations.html.twig'
                media:
                    template: '@SyliusAdmin/Product/Form/Sections/_media.html.twig'
