twig_hooks:
    hooks:
        'sylius_admin.product_association_type.update.content':
            form:
                template: '@SyliusAdmin/shared/crud/common/content/form.html.twig'
                configuration:
                    render_rest: false

        'sylius_admin.product_association_type.update.content.form':
            details:
                template: '@SyliusAdmin/product_association_type/form/details.html.twig'
            translations:
                template: '@SyliusAdmin/product_association_type/form/translations.html.twig'

        'sylius_admin.product_association_type.update.content.form.details':
            code:
                template: '@SyliusAdmin/product_association_type/form/details/code.html.twig'

        'sylius_admin.product_association_type.update.content.form.translations':
            name:
                template: '@SyliusAdmin/product_association_type/form/translations/name.html.twig'
