twig_hooks:
    hooks:
        'sylius_admin.common.component.navbar':
            menu:
                template: '@SyliusAdmin/shared/crud/common/navbar/menu.html.twig'
            items:
                template: '@SyliusAdmin/shared/crud/common/navbar/items.html.twig'
        'sylius_admin.common.component.navbar.items':
            notifications:
                component: 'sylius_admin:navbar:notifications'
            user_dropdown:
                template: '@SyliusAdmin/shared/crud/common/navbar/items/user.html.twig'
        'sylius_admin.common.component.navbar.menu':
            shop_preview:
                component: 'sylius_admin:navbar:shop_preview'
            search:
                template: '@SyliusAdmin/shared/crud/common/navbar/menu/search.html.twig'
