imports:
    - { resource: "@SyliusAdminBundle/Resources/config/grids/channel.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/country.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/currency.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/locale.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/order.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/payment_method.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_attribute.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_option.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_variant.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/promotion.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/promotion_coupon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/shipping_method.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/tax_category.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/tax_rate.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/zone.yml" }
