sylius_ui:
    events:
        sylius.admin.taxon.create.content:
            blocks:
                form:
                    template: '@SyliusAdmin/Taxon/Create/_form.html.twig'
                    context:
                        render_rest: false
        sylius.admin.taxon.create.content.form:
            blocks:
                tree:
                    component: 'SyliusAdmin.Taxon.TaxonTree'
                sections:
                    template: '@SyliusAdmin/Taxon/Form/_sections.html.twig'
        sylius.admin.taxon.create.content.form.sections:
            blocks:
                details:
                    template: '@SyliusAdmin/Taxon/Form/Sections/_details.html.twig'
                translations:
                    template: '@SyliusAdmin/Taxon/Form/Sections/_translations.html.twig'
                media:
                    template: '@SyliusAdmin/Taxon/Form/Sections/_media.html.twig'
        sylius.admin.taxon.create.content.form.sections.details:
            blocks:
                code:
                    template: '@SyliusAdmin/Taxon/Form/Sections/Details/_code.html.twig'
                parent:
                    template: '@SyliusAdmin/Taxon/Form/Sections/Details/_parent.html.twig'
                enabled:
                    template: '@SyliusAdmin/Taxon/Form/Sections/Details/_enabled.html.twig'
