sylius_grid:
    grids:
        sylius_admin_address_log_entry:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.address_log_entry.class%"
                    repository:
                        method: createByObjectIdQueryBuilder
                        arguments:
                            objectId: $objectId
            fields:
                action:
                    type: twig
                    label: sylius.ui.action
                    options:
                        template: "@SyliusAdmin/Address/Grid/Field/action.html.twig"
                loggedAt:
                    type: datetime
                    label: sylius.ui.logged_at
                    options:
                        format: d-m-Y H:i:s
                data:
                    type: twig
                    label: sylius.ui.changes
                    options:
                        template: "@SyliusAdmin/Address/Grid/Field/logData.html.twig"
