sylius_grid:
    grids:
        sylius_admin_catalog_promotion:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.catalog_promotion.class%"
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                label:
                    type: string
                    label: sylius.ui.label
                    sortable: ~
