sylius_grid:
    grids:
        sylius_admin_exchange_rate:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.exchange_rate.class%"
            sorting:
                ratio: desc
            fields:
                ratio:
                    type: string
                    label: sylius.ui.ratio
                    sortable: ~
                baseCurrency:
                    type: twig
                    label: sylius.ui.base_currency
                    path: .
                    options:
                        template: "@SyliusAdmin/ExchangeRate/Grid/Field/baseCurrencyName.html.twig"
                counterCurrency:
                    type: twig
                    label: sylius.ui.counter_currency
                    path: .
                    options:
                        template: "@SyliusAdmin/ExchangeRate/Grid/Field/counterCurrencyName.html.twig"
            filters:
                ratio:
                    type: string
                    label: sylius.ui.ratio
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
