sylius_grid:
    grids:
        sylius_admin_payment_payment_request:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.payment_request.class%"
                    repository:
                        method: createForPaymentQueryBuilder
                        arguments:
                            paymentId: $id
            sorting:
                createdAt: desc
            fields:
                hash:
                    type: string
                    label: sylius.ui.hash
                    sortable: ~
                method:
                    type: twig
                    label: sylius.ui.payment_method
                    path: .
                    options:
                        template: "@SyliusAdmin/payment/payment_request/grid/field/method.html.twig"
                action:
                    type: twig
                    label: sylius.ui.action
                    options:
                        template: "@SyliusAdmin/payment/payment_request/grid/field/action.html.twig"
                state:
                    type: twig
                    label: sylius.ui.state
                    options:
                        template: "@SyliusAdmin/payment/payment_request/grid/field/state.html.twig"
                createdAt:
                    type: twig
                    label: sylius.ui.creation_date
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/shared/grid/field/date.html.twig"
                        vars:
                            th_class: "w-1 text-center"
                updatedAt:
                    type: twig
                    label: sylius.ui.updating_date
                    sortable: ~
                    options:
                        template: "@SyliusAdmin/shared/grid/field/date.html.twig"
                        vars:
                            th_class: "w-1 text-center"
            filters:
                payment_method:
                    type: ux_translatable_autocomplete
                    label: sylius.ui.payment_method
                    form_options:
                        extra_options:
                            class: "%sylius.model.payment_method.class%"
                            translation_fields: [ name ]
                            choice_label: name
                    options:
                        fields: [ method.id ]
                action:
                    type: select
                    label: sylius.ui.action
                    form_options:
                        choices:
                            sylius.ui.authorize: authorize
                            sylius.ui.cancel: cancel
                            sylius.ui.capture: capture
                            sylius.ui.payout: payout
                            sylius.ui.refund: refund
                            sylius.ui.status: status
                            sylius.ui.sync: sync
                state:
                    type: select
                    label: sylius.ui.state
                    form_options:
                        choices:
                            sylius.ui.cancelled: cancelled
                            sylius.ui.completed: completed
                            sylius.ui.failed: failed
                            sylius.ui.new: new
                            sylius.ui.processing: processing
            actions:
                item:
                    show:
                        type: show
                        options:
                            link:
                                route: sylius_admin_payment_payment_request_show
                                parameters:
                                    hash: resource.hash
                                    paymentId: resource.payment.id
