sylius_grid:
    grids:
        sylius_admin_product_option:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product_option.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translation.name]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
