sylius_grid:
    grids:
        sylius_admin_product_taxons:
            extends: sylius_admin_product
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["expr:service('sylius.context.locale').getLocaleCode()", $id]
            sorting:
                position: asc
            fields:
                position:
                    type: twig
                    label: sylius.ui.position
                    path: .
                    sortable: productTaxon.position
                    options:
                        template: "@SyliusAdmin/product_taxon/grid/field/position.html.twig"
            filters:
                taxon:
                    type: string
                    enabled: false
                main_taxon:
                    type: string
                    enabled: false
            actions:
                main:
                    create:
                        type: create
                        enabled: false
                    update_positions:
                        type: update_product_taxon_positions
