sylius_grid:
    grids:
        sylius_admin_promotion_coupon:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.promotion_coupon.class%"
                    repository:
                        method: createQueryBuilderWithPromotion
                        arguments:
                            promotionId: $promotionId
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                usageLimit:
                    type: string
                    label: sylius.ui.usage_limit
                    sortable: ~
                perCustomerUsageLimit:
                    type: string
                    label: sylius.ui.per_customer_usage_limit
                    sortable: ~
                used:
                    type: string
                    label: sylius.ui.used
                    sortable: ~
                expiresAt:
                    type: datetime
                    label: sylius.ui.expires_at
                    sortable: ~
                    options:
                        format: d-m-Y
            filters:
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    generate:
                        type: generate_coupon
                    create:
                        type: create_coupon
                item:
                    update:
                        type: update_coupon
                    delete:
                        type: delete_coupon
