sylius_grid:
    grids:
        sylius_admin_promotion:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.promotion.class%"
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    options:
                        template: @SyliusAdmin/Grid/Field/nameAndDescription.html.twig
                couponBased:
                    type: twig
                    label: sylius.ui.coupons
                    options:
                        template: @SyliusAdmin/Grid/Field/yesNo.html.twig
                usage:
                    type: twig
                    label: sylius.ui.usage
                    path: .
                    options:
                        template: @SyliusAdmin/Promotion/Grid/Field/usage.html.twig
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name]
                couponBased:
                    type: boolean
                    label: sylius.ui.coupons
            actions:
                main:
                    create:
                        type: create
                item:
                    manage_coupons:
                        type: manage_coupons
                    update:
                        type: update
                    delete:
                        type: delete
