sylius_grid:
    grids:
        sylius_admin_route:
            driver:
                name: doctrine/phpcr-odm
                options:
                    class: "%sylius.model.route.class%"
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                name:
                    type: string
                    label: sylius.ui.name
            filters:
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
