sylius_grid:
    grids:
        sylius_admin_static_content:
            driver:
                name: doctrine/phpcr-odm
                options:
                    class: "%sylius.model.static_content.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                title:
                    type: string
                    label: sylius.ui.title
                body:
                    type: twig
                    label: sylius.ui.body
                    options:
                        template: SyliusAdminBundle:Grid/Field:truncate.html.twig
            filters:
                title:
                    type: string
                    label: sylius.ui.title
                body:
                    type: string
                    label: sylius.ui.body
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
