sylius_grid:
    grids:
        sylius_admin_static_content:
            driver:
                name: doctrine/phpcr-odm
                options:
                    class: "%sylius.model.static_content.class%"
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                title:
                    type: string
                    label: sylius.ui.title
            filters:
                title:
                    type: string
                    label: sylius.ui.title
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
