sylius_grid:
    grids:
        sylius_admin_tax_category:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.tax_category.class%"
            sorting:
                nameAndDescription: asc
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                nameAndDescription:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    sortable: name
                    options:
                        template: SyliusAdminBundle:Grid/Field:nameAndDescription.html.twig
            filters:
                name:
                    type: string
                    label: sylius.ui.name
                code:
                    type: string
                    label: sylius.ui.code
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
