# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_mailer:
    emails:
        order_confirmation_resent:
            subject: sylius.emails.order_confirmation.subject
            template: "@SyliusAdmin/Email/orderConfirmation.html.twig"
        shipment_confirmation:
            subject: sylius.emails.shipment_confirmation.subject
            template: "@SyliusAdmin/Email/shipmentConfirmation.html.twig"
        admin_password_reset:
            subject: sylius.emails.admin_password_reset.subject
            template: "@SyliusAdmin/Email/adminPasswordReset.html.twig"
