twig_hooks:
    hooks:
        'sylius_admin.customer_group.update.content':
            form:
                component: 'sylius_admin:customer_group:form'
                props:
                    resource: '@=_context.resource'
                    form: '@=_context.form'
                    template: '@SyliusAdmin/shared/crud/common/content/form.html.twig'
                configuration:
                    render_rest: false
                    method: 'PUT'
        
        'sylius_admin.customer_group.update.content.form':
            sections:
                template: '@SyliusAdmin/customer_group/form/sections.html.twig'

        'sylius_admin.customer_group.update.content.form.sections':
            general:
                template: '@SyliusAdmin/customer_group/form/sections/general.html.twig'

        'sylius_admin.customer_group.update.content.form.sections.general':
            default:
                enabled: false
            code:
                template: '@SyliusAdmin/customer_group/form/sections/general/code.html.twig'
            name:
                template: '@SyliusAdmin/customer_group/form/sections/general/name.html.twig'
