# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_ajax_taxon_root_nodes:
    path: /root-nodes
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findRootNodes

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_ajax_taxon_leafs:
    path: /leafs
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findChildren
                arguments:
                    parentCode: $parentCode

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_ajax_taxon_by_code:
    path: /leaf
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_ajax_taxon_by_name_phrase:
    path: /search
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByNamePart
                arguments:
                    phrase: expr:service('request_stack').getCurrentRequest().query.get('phrase', '')
                    locale: null
                    limit: 25
                    excludes: $excludes

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_ajax_generate_taxon_slug:
    path: /generate-slug/
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon_slug::generateAction
        _format: json
