twig_hooks:
    hooks:
        'sylius_admin.zone.create.content':
            form:
                component: 'sylius_admin:zone:form'
                data:
                    zone: '@=resource'
                    type: '@=resource.getType()'
                    form: '@=form'
                    parentMainHook: '@=parent_main_hook'
                    parentFallbackHook: '@=parent_fallback_hook'

        'sylius_admin.zone.create.content.form':
            sections:
                template: '@SyliusAdmin/zone/form/sections.html.twig'

        'sylius_admin.zone.create.content.form.sections':
            details:
                template: '@SyliusAdmin/zone/form/sections/details.html.twig'
            members:
                template: '@SyliusAdmin/zone/form/sections/members.html.twig'
                
        'sylius_admin.zone.create.content.form.sections.members':
            member:
                template: '@SyliusAdmin/zone/form/sections/members/member.html.twig'

        'sylius_admin.zone.create.content.form.sections.details':
            top:
                template: '@SyliusAdmin/zone/form/sections/details/top.html.twig'
            bottom:
                template: '@SyliusAdmin/zone/form/sections/details/bottom.html.twig'
        
        'sylius_admin.zone.create.content.form.sections.details.top':
            type:
                template: '@SyliusAdmin/zone/form/sections/details/top/type.html.twig'
            code:
                template: '@SyliusAdmin/zone/form/sections/details/top/code.html.twig'
        
        'sylius_admin.zone.create.content.form.sections.details.bottom':
            _name:
                template: '@SyliusAdmin/zone/form/sections/details/bottom/name.html.twig'
            scope:
                template: '@SyliusAdmin/zone/form/sections/details/bottom/scope.html.twig'
