imports:
    - { resource: "@SyliusUiBundle/Resources/config/app/config.yml" }

    - { resource: "@SyliusAdminBundle/Resources/config/app/sylius/sylius_mailer.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/address_log_entry.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/admin_user.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/channel.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/country.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/currency.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer_group.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer_order.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/exchange_rate.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/inventory.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/locale.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/order.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/payment.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/payment_method.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_association_type.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_attribute.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_from_taxon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_option.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_review.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_variant.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/promotion.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/promotion_coupon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/shipment.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/shipping_category.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/shipping_method.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/tax_category.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/tax_rate.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/taxon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/zone.yml" }

sylius_grid:
    templates:
        action:
            create_payment_method: "@SyliusAdmin/PaymentMethod/Grid/Action/create.html.twig"
            create_product_attribute: "@SyliusAdmin/ProductAttribute/Grid/Action/create.html.twig"
            generate_variants: "@SyliusAdmin/Product/Grid/Action/generateVariants.html.twig"
            update_product_positions: "@SyliusAdmin/Product/Grid/Action/updatePositions.html.twig"
            update_product_variant_positions: "@SyliusAdmin/ProductVariant/Grid/Action/updatePositions.html.twig"

liip_imagine:
    filter_sets:
        sylius_admin_product_original: ~
        sylius_admin_admin_user_avatar_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        sylius_admin_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_admin_product_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        sylius_admin_product_small_thumbnail:
            filters:
                thumbnail: { size: [150, 112], mode: outbound }
        sylius_admin_product_large_thumbnail:
            filters:
                thumbnail: { size: [550, 412], mode: outbound }

sonata_block:
    default_contexts: ~

sylius_ui:
    events:
        sylius.admin.index:
            blocks:
                before_header_legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        postfix: index.before_header 
                header:
                    template: "@SyliusAdmin/Crud/Index/_header.html.twig"
                    priority: 20
                after_header_legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        postfix: index.after_header
                content:
                    template: "@SyliusAdmin/Crud/Index/_content.html.twig"
                    priority: 10
                after_content: 
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        postfix: index.after_content 
        
        sylius.admin.index.stylesheets:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: index.stylesheets
                        
        sylius.admin.index.javascripts:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: index.javascripts
                        
        sylius.admin.index.header:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: index.header
                        
        sylius.admin.create:
            blocks:
                before_header_legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        postfix: create.before_header 
                header:
                    template: "@SyliusAdmin/Crud/Create/_header.html.twig"
                    priority: 20
                after_header_legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        postfix: create.after_header
                content:
                    template: "@SyliusAdmin/Crud/Create/_content.html.twig"
                    priority: 10
                after_content: 
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        postfix: create.after_content 
        
        sylius.admin.create.stylesheets:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: create.stylesheets
                        
        sylius.admin.create.javascripts:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: create.javascripts
                        
        sylius.admin.create.header:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: create.header
                        
        sylius.admin.create.form:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: create.form
                        
        sylius.admin.update:
            blocks:
                before_header_legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        postfix: update.before_header 
                header:
                    template: "@SyliusAdmin/Crud/Update/_header.html.twig"
                    priority: 20
                after_header_legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        postfix: update.after_header
                content:
                    template: "@SyliusAdmin/Crud/Update/_content.html.twig"
                    priority: 10
                after_content: 
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        postfix: update.after_content 
        
        sylius.admin.update.stylesheets:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: update.stylesheets
                        
        sylius.admin.update.javascripts:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: update.javascripts
                        
        sylius.admin.update.header:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: update.header
                        
        sylius.admin.update.form:
            blocks:
                legacy:
                    template: "@SyliusAdmin/Crud/Block/_legacySonataEvent.html.twig"
                    context:
                        postfix: update.form
       
        sylius.admin.layout.sidebar:
            blocks:
                top_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.admin.layout.sidebar_top
                logo:
                    template: "@SyliusAdmin/_logo.html.twig"
                    priority: 20
                menu:
                    template: "@SyliusAdmin/_menu.html.twig"
                    priority: 10
                down_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.admin.layout.sidebar_down
                        
        sylius.admin.layout.javascripts:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.admin.layout.javascripts
                        
        sylius.admin.layout.stylesheets:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.admin.layout.stylesheets

        sylius.admin.layout.topbar_left:
            blocks:
                sidebar_toggle:
                    template: "@SyliusAdmin/_sidebarToggle.html.twig"
                    priority: 30
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.admin.layout.topbar_left
                channel_links:
                    template: "@SyliusAdmin/_channelLinksWidget.html.twig"
                    priority: 20
                search:
                    template: "@SyliusAdmin/_search.html.twig"
                    priority: 10
                        
        sylius.admin.layout.topbar_middle:
            blocks:
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    context:
                        event: sylius.admin.layout.topbar_middle
                        
        sylius.admin.layout.topbar_right:
            blocks:
                notifications:
                    template: "@SyliusAdmin/_channelLinksWidget.html.twig"
                    priority: 30
                support:
                    template: "@SyliusAdmin/_support.html.twig"
                    priority: 20
                security:
                    template: "@SyliusAdmin/_security.html.twig"
                    priority: 10
                legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.admin.layout.topbar_right
