imports:
    - { resource: "@SyliusAdminBundle/Resources/config/grids/admin_user.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/channel.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/country.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/currency.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer_group.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/customer_order.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/exchange_rate.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/locale.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/order.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/payment_method.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_association_type.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_attribute.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_from_taxon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_option.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_review.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/product_variant.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/promotion.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/promotion_coupon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/shipping_category.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/shipping_method.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/tax_category.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/tax_rate.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/taxon.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/grids/zone.yml" }

sylius_resource:
    drivers:
        - doctrine/orm

sylius_grid:
    drivers:
        - doctrine/orm
    templates:
        action:
            default: "@SyliusUi/Grid/Action/default.html.twig"
            create: "@SyliusUi/Grid/Action/create.html.twig"
            delete: "@SyliusUi/Grid/Action/delete.html.twig"
            show: "@SyliusUi/Grid/Action/show.html.twig"
            update: "@SyliusUi/Grid/Action/update.html.twig"
            apply_transition: "@SyliusUi/Grid/Action/applyTransition.html.twig"

            create_product: "@SyliusAdmin/Product/Grid/Action/createProduct.html.twig"
            create_product_attribute: "@SyliusAdmin/ProductAttribute/Grid/Action/createProductAttribute.html.twig"
            create_zone: "@SyliusAdmin/Zone/Grid/Action/createZone.html.twig"
            generate_variants: "@SyliusAdmin/Product/Grid/Action/generateVariants.html.twig"
            manage_coupons: "@SyliusAdmin/Promotion/Grid/Action/manageCoupons.html.twig"
            manage_variants: "@SyliusAdmin/Product/Grid/Action/manageVariants.html.twig"
            update_product_taxons: "@SyliusAdmin/ProductTaxon/Grid/Action/update.html.twig"
        filter:
            string: "@SyliusUi/Grid/Filter/string.html.twig"
            boolean: "@SyliusUi/Grid/Filter/boolean.html.twig"

liip_imagine:
    filter_sets:
        sylius_admin_product_tiny_thumbnail:
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        sylius_admin_product_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
