# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_ui:
    events:
        sylius.admin.index.body:
            blocks:
                sidebar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_sidebar.html.twig'
                navbar:
                    template: '@SyliusAdmin/Shared/Crud/Common/_navbar.html.twig'
                content:
                    template: '@SyliusAdmin/Shared/Crud/Common/_content.html.twig'
        sylius.admin.common.navbar:
            blocks:
                items:
                    template: '@SyliusAdmin/Shared/Crud/Common/Navbar/_items.html.twig'
                menu:
                    template: '@SyliusAdmin/Shared/Crud/Common/Navbar/_menu.html.twig'
        sylius.admin.common.navbar.items:
            blocks:
                notifications:
                    component: 'SyliusAdminNavbarNotifications'
                user_dropdown:
                    template: '@SyliusAdmin/Shared/Crud/Common/Navbar/Items/_userDropdown.html.twig'
        sylius.admin.common.navbar.menu:
            blocks:
                search:
                    template: '@SyliusAdmin/Shared/Crud/Common/Navbar/Menu/_search.html.twig'
        sylius.admin.common.sidebar:
            blocks:
                logo:
                    template: '@SyliusAdmin/Shared/Crud/Common/Sidebar/_logo.html.twig'
                user_dropdown:
                    template: '@SyliusAdmin/Shared/Crud/Common/Sidebar/_userDropdown.html.twig'
                menu:
                    template: '@SyliusAdmin/Shared/Crud/Common/Sidebar/_menu.html.twig'
        sylius.admin.security.login:
            blocks:
                logo:
                    template: '@SyliusAdmin/Security/Login/_logo.html.twig'
                content:
                    template: '@SyliusAdmin/Security/Login/_content.html.twig'
        sylius.admin.security.login.content:
            blocks:
                header:
                    template: '@SyliusAdmin/Security/Login/Content/_header.html.twig'
                form:
                    template: '@SyliusAdmin/Security/Login/Content/_form.html.twig'
        sylius.admin.security.login.content.form:
            blocks:
                username_field:
                    template: '@SyliusAdmin/Security/Login/Content/Form/_usernameField.html.twig'
                password_field:
                    template: '@SyliusAdmin/Security/Login/Content/Form/_passwordField.html.twig'
                remember_me_field:
                    template: '@SyliusAdmin/Security/Login/Content/Form/_rememberMeField.html.twig'
                submit_button:
                    template: '@SyliusAdmin/Security/Login/Content/Form/_submitButton.html.twig'
