twig_hooks:
    hooks:
        'sylius_admin.product.show.content':
            page_body:
                template: '@SyliusAdmin/product/show/content/page_body.html.twig'

        'sylius_admin.product.show.content.header.title_block':
            title:
                template: '@SyliusAdmin/product/show/content/header/title_block/title.html.twig'
            actions:
                template: '@SyliusAdmin/product/show/content/header/title_block/actions.html.twig'
                
        'sylius_admin.product.show.content.header.title_block.actions':
            edit:
                template: '@SyliusAdmin/shared/crud/show/content/header/title_block/actions/edit.html.twig'
            view_in_store:
                template: '@SyliusAdmin/product/common/header/title_block/actions/view_in_store.html.twig'

        'sylius_admin.product.show.content.page_body':
            details:
                template: '@SyliusAdmin/product/show/content/page_body/details.html.twig'
            translations:
                template: '@SyliusAdmin/product/show/content/page_body/translations.html.twig'
            taxonomy:
                template: '@SyliusAdmin/product/show/content/page_body/taxonomy.html.twig'
            associations:
                template: '@SyliusAdmin/product/show/content/page_body/associations.html.twig'
            options:
                template: '@SyliusAdmin/product/show/content/page_body/options.html.twig'
            attributes:
                template: '@SyliusAdmin/product/show/content/page_body/attributes.html.twig'
            media:
                template: '@SyliusAdmin/product/show/content/page_body/media.html.twig'
                
        'sylius_admin.product.show.content.page_body.attributes#head':
            translatable_head:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/translatable/head/name.html.twig'
            non_translatable_head:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/non_translatable/head/name.html.twig'
            
        'sylius_admin.product.show.content.page_body.attributes#body':
            translatable_body:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/translatable.html.twig'
            non_translatable_body:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/non_translatable.html.twig'
        
        'sylius_admin.product.show.content.page_body.attributes.translatable':
            name:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/translatable/body/name.html.twig'
            value:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/translatable/body/value.html.twig'
                
        'sylius_admin.product.show.content.page_body.attributes.non_translatable':
            name:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/non_translatable/body/name.html.twig'
            value:
                template: '@SyliusAdmin/product/show/content/page_body/attributes/non_translatable/body/value.html.twig'

        'sylius_admin.product.show.content.page_body.translations':
            product_name:
                template: '@SyliusAdmin/product/show/content/page_body/translation_content/product_name.html.twig'
            slug:
                template: '@SyliusAdmin/product/show/content/page_body/translation_content/slug.html.twig'
            description:
                template: '@SyliusAdmin/product/show/content/page_body/translation_content/description.html.twig'
            short_description:
                template: '@SyliusAdmin/product/show/content/page_body/translation_content/short_description.html.twig'
            meta_keywords:
                template: '@SyliusAdmin/product/show/content/page_body/translation_content/meta_keywords.html.twig'
            meta_description:
                template: '@SyliusAdmin/product/show/content/page_body/translation_content/meta_description.html.twig'

        'sylius_admin.product.show.content.page_body.taxonomy':
            main_taxon:
                template: '@SyliusAdmin/product/show/content/page_body/taxonomy/main_taxon.html.twig'
            product_taxons:
                template: '@SyliusAdmin/product/show/content/page_body/taxonomy/product_taxons.html.twig'

        'sylius_admin.product.show.content.page_body.details':
            simple_product:
                template: '@SyliusAdmin/product/show/content/page_body/details/simple_product.html.twig'
            configurable_product:
                template: '@SyliusAdmin/product/show/content/page_body/details/configurable_product.html.twig'

        'sylius_admin.product.show.content.page_body.details.simple_product#head':
            product:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/product.html.twig'
            enabled:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/enabled.html.twig'
            tracked:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/tracked.html.twig'
            shipping_required:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/shipping_required.html.twig'
            tax_category:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/tax_category.html.twig'
            current_stock:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/current_stock.html.twig'
                
        'sylius_admin.product.show.content.page_body.details.simple_product#tab':
            product:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/product.html.twig'
            enabled:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/enabled.html.twig'
            tracked:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/tracked.html.twig'
            shipping_required:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/shipping_required.html.twig'
            tax_category:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/tax_category.html.twig'
            current_stock:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/current_stock.html.twig'


        'sylius_admin.product.show.content.page_body.details.simple_product#details':
            pricing:
                template: '@SyliusAdmin/product/show/content/page_body/details/simple_product/details/pricing.html.twig'
            shipping:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping.html.twig'

        'sylius_admin.product.show.content.page_body.details.simple_product.shipping':
            shipping_category:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/shipping_category.html.twig'
            width:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/width.html.twig'
            height:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/height.html.twig'
            depth:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/depth.html.twig'
            weight:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/weight.html.twig'
        
        'sylius_admin.product.show.content.page_body.details.simple_product.pricing#head':
            channel:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/channel.html.twig'
            price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/price.html.twig'
            original_price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/original_price.html.twig'
            lowest_price_before_the_discount:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/lowest_price_before_the_discount.html.twig'
            discounted_by:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/discounted_by.html.twig'
            price_history:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/price_history.html.twig'


        'sylius_admin.product.show.content.page_body.details.simple_product.pricing#body':
            channel:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/channel.html.twig'
            price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/price.html.twig'
            original_price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/original_price.html.twig'
            lowest_price_before_the_discount:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/lowest_price_before_the_discount.html.twig'
            applied_promotions:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/applied_promotions.html.twig'
            price_history:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/price_history.html.twig'
                
        'sylius_admin.product.show.content.page_body.details.configurable_product#head':
            details_button:
                template: '@SyliusAdmin/product/show/content/page_body/details/configurable_product/head/details_button.html.twig'
            product:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/product.html.twig'
            enabled:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/enabled.html.twig'
            options:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/options.html.twig'
            tracked:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/tracked.html.twig'
            shipping_required:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/shipping_required.html.twig'
            tax_category:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/tax_category.html.twig'
            current_stock:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/head/current_stock.html.twig'
            edit_button:
                template: '@SyliusAdmin/product/show/content/page_body/details/configurable_product/head/edit_button.html.twig'


        'sylius_admin.product.show.content.page_body.details.configurable_product#tab':
            details_button:
                template: '@SyliusAdmin/product/show/content/page_body/details/configurable_product/tab/details_button.html.twig'
            product:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/product.html.twig'
            enabled:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/enabled.html.twig'
            options:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/options.html.twig'
            tracked:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/tracked.html.twig'
            shipping_required:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/shipping_required.html.twig'
            tax_category:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/tax_category.html.twig'
            current_stock:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/tab/current_stock.html.twig'
            edit_button:
                template: '@SyliusAdmin/product/show/content/page_body/details/configurable_product/tab/edit_button.html.twig'

        'sylius_admin.product.show.content.page_body.details.configurable_product#details':
            pricing:
                template: '@SyliusAdmin/product/show/content/page_body/details/configurable_product/details/pricing.html.twig'
            shipping:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping.html.twig'

        'sylius_admin.product.show.content.page_body.details.configurable_product.pricing#head':
            channel:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/channel.html.twig'
            price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/price.html.twig'
            original_price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/original_price.html.twig'
            lowest_price_before_the_discount:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/lowest_price_before_the_discount.html.twig'
            discounted_by:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/discounted_by.html.twig'
            price_history:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/head/price_history.html.twig'

        'sylius_admin.product.show.content.page_body.details.configurable_product.pricing#body':
            channel:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/channel.html.twig'
            price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/price.html.twig'
            original_price:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/original_price.html.twig'
            lowest_price_before_the_discount:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/lowest_price_before_the_discount.html.twig'
            applied_promotions:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/applied_promotions.html.twig'
            price_history:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/pricing/body/price_history.html.twig'

        'sylius_admin.product.show.content.page_body.details.configurable_product.shipping':
            shipping_category:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/shipping_category.html.twig'
            width:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/width.html.twig'
            height:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/height.html.twig'
            depth:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/depth.html.twig'
            weight:
                template: '@SyliusAdmin/product/show/content/page_body/details/shared/shipping/weight.html.twig'
