twig_hooks:
    hooks:
        'sylius_admin.country.create.content':
            form:
                component: 'SyliusAdmin.Country.CountryType'
                props:
                    country: '@=_context.resource'
                    form: '@=_context.form'
                    parentMainHook: '@=_context.parent_main_hook'
                    parentFallbackHook: '@=_context.parent_fallback_hook'

        'sylius_admin.country.create.content.form':
            sections:
                template: '@SyliusAdmin/Country/Form/_sections.html.twig'

        'sylius_admin.country.create.content.form.sections':
            details:
                template: '@SyliusAdmin/Country/Form/Sections/_details.html.twig'
            provinces:
                template: '@SyliusAdmin/Country/Form/Sections/_provinces.html.twig'

        'sylius_admin.country.create.content.form.sections.details':
            code:
                template: '@SyliusAdmin/Country/Form/Sections/Details/_code.html.twig'
            enabled:
                template: '@SyliusAdmin/Country/Form/Sections/Details/_enabled.html.twig'
