sylius_admin_api_taxon:
    resource: "@SyliusAdminBundle/Resources/config/routing/api/taxon.yml"
    prefix: /taxons

sylius_admin_api_product:
    resource: "@SyliusAdminBundle/Resources/config/routing/api/product.yml"
    prefix: /products
