sylius_admin_catalog_promotion:
    resource: |
        alias: sylius.catalog_promotion
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index', 'create', 'update']
        redirect: update
        grid: sylius_admin_catalog_promotion
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_discounts_on_product_catalog
                templates:
                    form: "@SyliusAdmin/CatalogPromotion/_form.html.twig"
            index:
                icon: bookmark
    type: sylius.resource
