sylius_admin_customer:
    resource: |
        alias: sylius.customer
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_customer
        vars:
            all:
                subheader: sylius.ui.manage_your_customers
                templates:
                    form: SyliusAdminBundle:Customer:_form.html.twig
            index:
                icon: users
    type: sylius.resource
    defaults:
        _sylius:
            permission: true
