sylius_admin_order:
    resource: |
        alias: sylius.order
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['create', 'update', 'show']
        grid: sylius_admin_order
        vars:
          all:
              subheader: sylius.ui.process_your_orders
          index:
              icon: cart
    type: sylius.resource

sylius_admin_order_show:
    path: /orders/{id}
    defaults:
        _controller: sylius.controller.order:showAction
        _sylius:
            section: admin
            template: SyliusAdminBundle:Order:show.html.twig

sylius_admin_order_cancel:
    path: /orders/{id}/cancel
    methods: [PUT]
    defaults:
        _controller: sylius.controller.order:applyStateMachineTransitionAction
        _sylius:
            state_machine:
                graph: sylius_order
                transition: cancel
            redirect: referer

sylius_admin_order_payment_complete:
    path: /orders/{id}/payments/{paymentId}/complete
    methods: [PUT]
    defaults:
        _controller: sylius.controller.payment:applyStateMachineTransitionAction
        _sylius:
            repository:
                method: findByOrderIdAndId
                arguments:
                    id: $id
                    paymentId: $paymentId
            state_machine:
                graph: sylius_payment
                transition: complete
            redirect: referer
