sylius_admin_payment:
    resource: |
        alias: sylius.payment
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        only: ['index']
        grid: sylius_admin_payment
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_payments
            index:
                icon: payment
    type: sylius.resource

sylius_admin_payment_complete:
    path: /payments/{id}/complete
    methods: [PUT]
    defaults:
        _controller: sylius.controller.payment::applyStateMachineTransitionAction
        _sylius:
            event: complete
            section: admin
            permission: true
            state_machine:
                graph: sylius_payment
                transition: complete
            redirect: sylius_admin_payment_index
            flash: sylius.payment.completed

sylius_admin_payment_payment_request_index:
    path: /payments/{id}/payment_requests
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_request::indexAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/payment/payment_request/index.html.twig"
            grid: sylius_admin_payment_payment_request
            
sylius_admin_payment_payment_request_show:
    path: /payments/{paymentId}/payment_requests/{hash}
    methods: [GET]
    defaults:
        _controller: sylius.controller.payment_request::showAction
        _sylius:
            section: admin
            permission: true
            template: "@SyliusAdmin/payment/payment_request/show.html.twig"
            repository:
                method: findOneByPaymentId
                arguments:
                    hash: $hash
                    paymentId: $paymentId
