sylius_admin_product_taxon_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product::indexAction
        _sylius:
            section: admin
            permission: true
            grid: sylius_admin_product_taxons
            template: "@SyliusAdmin/product_taxon/index.html.twig"
            vars:
                subheader: sylius.ui.manage_your_product_catalog
                icon: cube

sylius_admin_product_taxon_update_position:
    path: /update
    methods: [PUT]
    defaults:
        _controller: sylius.controller.product_taxon::updateProductTaxonsPositionsAction
