sylius_admin_shipment:
    resource: |
        alias: sylius.shipment
        section: admin
        templates: "@SyliusAdmin\\Crud"
        only: ['index']
        grid: sylius_admin_shipment
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_shipments
            index:
                icon: truck
    type: sylius.resource

sylius_admin_shipment_ship:
    path: /shipments/{id}/ship
    methods: [PUT]
    defaults:
        _controller: Sylius\Bundle\AdminBundle\Action\ShipShipmentAction
        _sylius:
            section: admin
            permission: true

sylius_admin_shipment_resend_confirmation_email:
    path: /shipments/{id}/resend-confirmation-email
    methods: [GET]
    defaults:
        _controller: Sylius\Bundle\AdminBundle\Action\ResendShipmentConfirmationEmailAction
