sylius_admin_tax_rate:
    resource: |
        alias: sylius.tax_rate
        section: admin
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: sylius_admin_tax_rate
        vars:
          all:
              subheader: sylius.ui.manage_taxation_of_your_products
              templates:
                  form: SyliusAdminBundle:TaxRate:_form.html.twig
          index:
              icon: money
    type: sylius.resource
    defaults:
        _sylius:
            permission: true
