sylius_admin_taxon:
    resource: |
        alias: sylius.taxon
        section: admin
        templates: SyliusAdminBundle:Taxon
        except: ['show', 'index']
        redirect: update
        vars:
            all:
                subheader: sylius.ui.manage_categorization_of_your_products
                templates:
                    form: SyliusAdminBundle:Taxon:_form.html.twig
    type: sylius.resource

sylius_admin_taxon_index:
    path: /taxons/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_admin_taxon_create
        permanent: true

sylius_admin_taxon_tree:
    path: /taxons/tree
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: SyliusAdminBundle:Taxon:index.html.twig
            repository:
                method: findRootNodes
    host: "localhost"

sylius_admin_api_taxon_index:
    path: api/taxons
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _format: json
        _sylius:
            grid: sylius_admin_taxon
