twig_hooks:
    hooks:
        'sylius_admin.security.request_password_reset':
            logo:
                template: '@SyliusAdmin/security/login/logo.html.twig'
            content:
                template: '@SyliusAdmin/security/login/content.html.twig'

        'sylius_admin.security.request_password_reset.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
            form:
                template: '@SyliusAdmin/security/request_password_reset/content/form.html.twig'

        'sylius_admin.security.request_password_reset.content.form':
            email:
                template: '@SyliusAdmin/security/request_password_reset/content/form/email.html.twig'
            submit:
                template: '@SyliusAdmin/security/request_password_reset/content/form/submit.html.twig'
