twig_hooks:
    hooks:
        'sylius_admin.security.reset_password':
            logo:
                template: '@SyliusAdmin/security/login/logo.html.twig'
            content:
                template: '@SyliusAdmin/security/login/content.html.twig'

        'sylius_admin.security.reset_password.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
            form:
                template: '@SyliusAdmin/security/reset_password/content/form.html.twig'

        'sylius_admin.security.reset_password.content.form':
            error:
                template: '@SyliusAdmin/security/reset_password/content/form/error.html.twig'
            password:
                template: '@SyliusAdmin/security/reset_password/content/form/password.html.twig'
            submit:
                template: '@SyliusAdmin/security/request_password_reset/content/form/submit.html.twig'
