sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_request.show.content':
            sections:
                template: '@SyliusAdmin/payment_request/show/content/sections.html.twig'
        
        'sylius_admin.payment_request.show.content.header':
            breadcrumbs:
                template: '@SyliusAdmin/payment_request/show/content/header/breadcrumbs.html.twig'

        'sylius_admin.payment_request.show.content.sections':
            general:
                template: '@SyliusAdmin/payment_request/show/content/sections/general.html.twig'

        'sylius_admin.payment_request.show.content.sections#left':
            payload:
                template: '@SyliusAdmin/payment_request/show/content/sections/payload.html.twig'

        'sylius_admin.payment_request.show.content.sections#right':
            response_data:
                template: '@SyliusAdmin/payment_request/show/content/sections/response_data.html.twig'

        'sylius_admin.payment_request.show.content.sections.general':
            hash:
                template: '@SyliusAdmin/payment_request/show/content/sections/general/hash.html.twig'
            method:
                template: '@SyliusAdmin/payment_request/show/content/sections/general/method.html.twig'
            action:
                template: '@SyliusAdmin/payment_request/show/content/sections/general/action.html.twig'
            state:
                template: '@SyliusAdmin/payment_request/show/content/sections/general/state.html.twig'
            created_at:
                template: '@SyliusAdmin/payment_request/show/content/sections/general/created_at.html.twig'
            updated_at:
                template: '@SyliusAdmin/payment_request/show/content/sections/general/updated_at.html.twig'
