sylius_admin_address_log_entry_index:
    path: /log-entry/{objectId}
    methods: [GET]
    defaults:
        _controller: sylius.controller.address_log_entry:indexAction
        _sylius:
            template: "@SyliusAdmin/Order/History/addressIndex.html.twig"
            grid: sylius_admin_address_log_entry
            section: admin
            permission: true
            vars:
                route:
                    parameters:
                        objectId: $objectId
