# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_partial_catalog_promotion_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.catalog_promotion::showAction
        _sylius:
            template: $template
            vars: $vars
            permission: true
