# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_partial_channel_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.channel::indexAction
        _sylius:
            repository:
                method: findAll
            template: $template
            permission: true
