# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_partial_order_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order::indexAction
        _sylius:
            repository:
                method: findLatest
                arguments:
                    - '!!int $count'
            template: $template
            permission: true

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_partial_order_latest_in_channel:
    path: /latest/{channelCode}/{count}
    methods: [GET]
    defaults:
        _controller: sylius.controller.order::indexAction
        _sylius:
            repository:
                method: findLatestInChannel
                arguments:
                    count: '!!int $count'
                    channel: expr:notFoundOnNull(service('sylius.repository.channel').findOneByCode($channelCode))
            template: $template
            permission: true
