# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_partial_taxon_tree:
    path: /tree
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::indexAction
        _sylius:
            template: $template
            repository:
                method: findHydratedRootNodes
            permission: true

# This route is deprecated since Sylius 1.14.0 and will be removed in 2.0.0.
sylius_admin_partial_taxon_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon::showAction
        _sylius:
            template: $template
            vars: $vars
            permission: true
