sylius_admin_partial_taxon_tree:
    path: /tree
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:indexAction
        _sylius:
            template: @SyliusAdmin/Taxon/Partial/_tree.html.twig
            repository:
                method: findRootNodes
